name:                stuff-hs
version:             0.1.0.0
github:              "githubuser/stuff-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/stuff-hs#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- unix
- containers
- io-streams
- binary
- wire-streams
- network
- transformers
- stm
- async
- time

library:
  source-dirs: src

executables:
  stuff-server:
    main:                Server.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Server
    dependencies:
    - stuff-hs
  stuff-client:
    main:                Client.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Client
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - stuff-hs

tests:
  stuff-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    dependencies:
    - stuff-hs
